<sexpr> ::= <atom> | <list>
<list> ::= "(" <atom> <sexpr>* ")"
<atom> ::= <lit> | <symbol> | <vector>
<vector> ::= "[" <sexpr>* "]"
<lit> ::= <number> |<bool> | <string>
<number> ::= <int> | <real>
<int> ::= <digit>+
<real> ::= <digit>+ "." <digit>+
<string> ::= '"' <char>* '"'
<bool> ::= "true" | "false"
<symbol> ::= <letter> <char>*
<char> ::= "_" | <letter> | <digit>
<letter> ::= [a-zA-Z]
<digit> ::= [0-9]
