<sexpr> ::= <atom> | <list>
<list> ::= "(" <sexpr>* ")"
<atom> ::= <lit> | <symbol>
<lit> ::= <number> |<bool> | <string>
<number> ::= <int> | <real>
<int> ::= <digit>+
<real> ::= <digit>+ "." <digit>+
<bool> ::= "true" | "false"
<string> ::= '"' <character>* '"'
<symbol> ::= <letter> <letter>*
<letter> ::= [a-zA-Z]
<vector> ::= "[" <sexpr>* "]"