sexpr = atom | synList | dataList | variadic
synList = "(" atom sexpr* ")"
dataList = "[" sexpr* "]"
variadic = symbol "..."
atom = lit | symbol | vector | path
path = symbol ("." symbol)+
vector = "#[" sexpr* "]"
lit = number | bool | string
number = int | real

# Tokens/Terminals
int = [0-9]+
real = digit+ "." digit+
string = '"' char* '"'
bool = "true" | "false"
symbol = letter char*
char = "_" | letter | digit
letter = [a-zA-Z]
digit = [0-9]
